### ISSUE TITLE
Unnecessary variable

### ISSUE THREAD

**Issue by bbehrang** [ValeronMEN/CSharpRepos#7]
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/Eurozone.cs#L16

Since the city neighbours are added to a list, number of neighbours can be read using the element count or length of the list and another separate variable for storing the number of neighbours is redundant. This can help the code to be dynamically adjustable should number of neighbours change anytime later without re-rewriting the constant.

**Comment by ValeronMEN** [comment]
'numberOfNeighbours' variable provides a constant to avoid magic numbers. This variable works like a stop to finish the loop in setCityNeighbours method https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/Eurozone.cs#L35
to avoid excessive running through the cycle. There's no sense to search for 5-th neighbour, because there's only 4

Close the issue, if you don't have any questions

**Comment by bbehrang** [comment]
Why do you need another variable when you can access the number of neighbours using list methods?

**Comment by ValeronMEN** [comment]
This variable is used in "setCityNeighbours()" method. On that stage we pick a city and go through all of the others to find connections. From where can I get '4'?
